name: "\U0001F527 General Issue"
description: Create a general issue about the website to be added to the UK TRE Community project board
body:
  - type: markdown
    attributes:
      value: |
        Thank you for being involved in the UK TRE Community!

        You should use this template for any general issue associated with the UK TRE Community website.

        This issue will be added to the backlog of our project board. If you would like to take it on, please assign it to yourself!

        All issues need to have someone assigned to/owning them in order to progress. Whilst this is not the case we'll keep the issue safe in the backlog!
  - type: textarea
    id: detail
    attributes:
      label: Detail
      description: Please explain your issue in detail
    validations:
      required: true
  - type: textarea
    id: actions
    attributes:
      label: Actions
      description: Please add any actions to be undertaken below. You can create a checklist by typing `- [ ] x` for each action point
    validations:
      required: true
  - type: textarea
    id: tags
    attributes:
      label: Who can help
      description: Tag anyone who you think will be interested or who can help by typing `@` followed by their GitHub username.
    validations:
      required: false
